spring:
  profiles:
    active: mysql,mail  # 激活的配置文件后缀
  mail:
    host: smtp.qq.com
    username: 2823626561@qq.com
    password: phuggewtwvgwdecf  # 注意：生产环境建议用环境变量注入
    default-encoding: utf-8
    protocol: smtps
    port: 465

logging:
  level:
    org.springframework.cache: DEBUG
    com.alibaba.nacos: INFO
    org.springframework.boot.autoconfigure.jdbc: DEBUG