easy-es:
  enable: true # 默认为true,若为false时,则认为不启用本框架
  address: 47.108.31.249:9200  #填你的es连接地址
  keep-alive-millis: 30000 # 心跳策略时间 单位:ms
  connect-timeout: 5000 # 连接超时时间 单位:ms
  socket-timeout: 600000 # 通信超时时间 单位:ms
  request-timeout: 5000 # 请求超时时间 单位:ms
  connection-request-timeout: 5000 # 连接请求超时时间 单位:ms
  max-conn-total: 100 # 最大连接数 单位:个
  max-conn-per-route: 100 # 最大连接路由数 单位:个
  # username: 有设置才填写,非必须
  # password: 有设置才填写,非必须
