server:
  port: 8083


    
  # Kafka 配置 (仅保留应用特定配置，通用配置由 share_kafka.yaml 提供)
  kafka:
    enable_mongo: true
    consumer:
      group-id: blog-ai-group

mybatis-plus:
  global-config:
    enable-sql-runner: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#by zhengkai.blog.csdn.net
#mybatis-plus配置控制台打印完整带参数SQL语句
